#!/bin/bash
# Script to help download ThetaTerminal.jar

echo "=== ThetaTerminal.jar Download Helper ==="
echo ""
echo "Option 1: If you have gcloud CLI on your local machine:"
echo "  gcloud compute scp ~/Desktop/ThetaTerminal.jar YOUR_INSTANCE_NAME:~/fntx-trading/thetadata/"
echo ""
echo "Option 2: Using curl with direct download link:"
echo "  If you can get a direct download URL from Google Drive, run:"
echo "  curl -L 'YOUR_DIRECT_URL' -o ~/fntx-trading/thetadata/ThetaTerminal.jar"
echo ""
echo "Option 3: Upload to the VM via VNC:"
echo "  1. Connect to VNC (35.194.231.94:5901)"
echo "  2. Open Firefox in the desktop"
echo "  3. Download from your Google Drive link"
echo "  4. Move to ~/fntx-trading/thetadata/"
echo ""
echo "Option 4: Python simple HTTP server (from your local machine):"
echo "  On your local machine:"
echo "    cd ~/Desktop"
echo "    python3 -m http.server 8888"
echo "  Then on this VM:"
echo "    wget YOUR_LOCAL_IP:8888/ThetaTerminal.jar -O ~/fntx-trading/thetadata/ThetaTerminal.jar"