# FNTX Agent Configuration

app:
  name: "FNTX Agent"
  version: "0.1.0"
  environment: "development"

trading:
  default_strategy: "spy-0dte"
  risk_per_trade: 0.02  # 2% risk per trade
  max_positions: 5
  stop_loss_multiplier: 3.5
  
enterprise:
  profit_split:
    pool: 0.80  # 80% to enterprise pool
    fee: 0.20   # 20% performance fee
  min_contribution: 100  # Minimum USD to join pool
  
blockchain:
  network: "polygon"
  rpc_url: "${POLYGON_RPC_URL}"
  humanity_protocol:
    contract_address: "${HUMANITY_CONTRACT_ADDRESS}"
    
tokens:
  fntx:
    total_supply: 1000000000  # 1 billion
    decimals: 18
  soul:
    initial_balance: 100
    daily_regeneration: 10
    
database:
  host: "${DB_HOST:-localhost}"
  port: "${DB_PORT:-5432}"
  name: "${DB_NAME:-fntx}"
  user: "${DB_USER:-fntx}"
  password: "${DB_PASSWORD}"

redis:
  host: "${REDIS_HOST:-localhost}"
  port: "${REDIS_PORT:-6379}"
  
api:
  host: "0.0.0.0"
  port: 8000
  cors_origins: ["http://localhost:3000"]
  
mcp:
  host: "0.0.0.0"
  port: 8001
  
logging:
  level: "INFO"
  format: "json"
  
security:
  jwt_secret: "${JWT_SECRET}"
  jwt_expiry: 86400  # 24 hours